### ISSUE TITLE
Allow user to refresh results from the WCIF after matching the scramble sets

### ISSUE THREAD

**Issue by Goosly** [thewca/scrambles-matcher#7]
I want to be able to do the following:

1. Match scrambles
2. Load the results from the WCIF into Scrambles Matcher
3. Download the results json
4. Verify the results by submitting  on the WCA site - this may give me some errors and warnings
5. Fix the errors and warning in WCA Live + synchronize
Repeat 2-5 until I don't have any errors or warnings anymore

Currently I must refresh Scrambles Matcher and match scrambles again because fetching the results from the WCIF is the first step (before matching scrambles), instead of the second step (after matching scrambles)

**Comment by viroulep** [comment]
>fetching the results from the WCIF is the first step (before matching scrambles), instead of the second step (after matching scrambles)

We need the WCIF to match scrambles to it, and it has the results in it, so it simply needs to be in this order.

A system for updating results in-place would be nice (similarly to the "sync" button of WCA Live basically).
Given we are bringing WCIF to TNoodle and plan on directly uploading results to the appropriate temporary tables on the WCA website (to simply avoid having to submit a json manually), it's probably simpler to just wait for this.

In the meantime there is an easy "workaround": you can use scrambles matcher as a simple WCIF to results json converter and download the results json without matching scrambles at all.
Then you can upload it to the WCA website, fix errors/warnings (obviously there will still be one error about missing scrambles!), and match the scrambles when only the scrambles error remains.

**Comment by Goosly** [comment]
Thanks for the explanation, I'll try the workaround next time!
